# -*- coding: utf-8 -*-
"""LangChain_RAG_basic chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0K6pIKn9WnoXYh0nZfFRzsXBoKfVoOJ
"""

!pip install -q langchain langchain-community langchain-huggingface langchain-text-splitters pypdf faiss-cpu sentence-transformers transformers torch

from google.colab import files

uploaded = files.upload()

from langchain_community.document_loaders import PyPDFLoader

pdf_name = list(uploaded.keys())[0]

loader = PyPDFLoader(pdf_name)

documents = loader.load()

print("Number of pages:", len(documents))

print(documents[0].page_content[:1000])

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

chunks = text_splitter.split_documents(documents)

print("Original pages:", len(documents))
print("Total chunks:", len(chunks))

print(chunks[0].page_content)

print(chunks[0].metadata)

from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding model loaded!")

from langchain_community.vectorstores import FAISS

vectorstore = FAISS.from_documents(
    chunks,
    embeddings
)

print("Vector database created!")

retriever = vectorstore.as_retriever(
    search_kwargs={"k": 3}
)

query = "What is the main topic of this document?"

results = retriever.invoke(query)

print("Retrieved chunks:", len(results))

for i, result in enumerate(results):

    print(f"\n========== RESULT {i+1} ==========")
    print(result.page_content)
    print("\nMetadata:", result.metadata)

from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM
)

from langchain_huggingface import HuggingFacePipeline

model_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSeq2SeqLM.from_pretrained(
    model_name
)

print("FLAN-T5 loaded!")

question = "What is HRSID?"

results = retriever.invoke(question)

for i, doc in enumerate(results):

    print(f"\n===== RESULT {i+1} =====")
    print(doc.page_content)
    print("\nSOURCE:", doc.metadata)

question = "What is the purpose of the HRSID dataset?"

results = retriever.invoke(question)

for i, doc in enumerate(results):

    print(f"\n===== RESULT {i+1} =====")
    print(doc.page_content)
    print("\nSOURCE:", doc.metadata)

questions = [
    "What is HRSID?",
    "What is the purpose of the HRSID dataset?",
    "What type of images are used in HRSID?",
    "What is SAR?",
    "What are the challenges in ship detection?"
]

for question in questions:

    print("\n" + "="*70)
    print("QUESTION:", question)
    print("="*70)

    results = retriever.invoke(question)

    for i, doc in enumerate(results):
        print(f"\n--- Retrieved Chunk {i+1} ---")
        print(doc.page_content[:1000])
        print("Source:", doc.metadata)

from langchain_core.prompts import PromptTemplate

prompt = PromptTemplate(
    template="""
Answer the question using ONLY the context provided below.

If the answer is not present in the context, say:
"I don't know based on the provided document."

Context:
{context}

Question:
{question}

Answer:
""",
    input_variables=["context", "question"]
)

print("Prompt created!")

from langchain_core.runnables import RunnablePassthrough

def format_documents(docs):
    return "\n\n".join(
        doc.page_content for doc in docs
    )

rag_chain = (
    {
        "context": retriever | format_documents,
        "question": RunnablePassthrough()
    }
    | prompt
)

print("RAG chain created!")

question = "What is HRSID?"

result = rag_chain.invoke(question)

print(result)

